name: Dev deploy

on: 
  push:
    branches:
      - development
      
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 16
        
      - name: Insall dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy to Hostinger - Development
        uses: appleboy/ssh-action@master
        with:
          host: 82.180.142.194
          port: 65002
          username: u478091396
          password: Shubham@28
          script: |
            cd domains/codemerge.tech/public_html/nitiv2/dev
            rm -rf
            ls
            cp -R ./build/* .
