name: Dev deploy

on: 
  push:
    branches:
      - development
      
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 16
        
      - name: Insall dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy to Hostinger - Development
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.HOST }}
          remote-user: ${{ secrets.USERNAME }}
          remote-host: ${{ secrets.HOST }}
          remote-port: ${{ secrets.PORT }}
          script: |
            cd /path/to/hostinger/public_html/main
            rm -rf *
            cp -R ./build/* .
